# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'Examples' do
    
   pod 'PaytomatSDK' 
  # Pods for Examples

  target 'ExamplesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
