platform :ios, '9.0'
use_frameworks!

target 'Examples' do
    
    pod 'PaytomatSDK', :path => "../"
  # Pods for Examples

  target 'ExamplesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
