platform :ios, '11.0'
use_frameworks!

target 'Examples' do
    
    pod 'MyEOSWalletSDK', :git => 'https://github.com/HvrlK/MyEOSWalletSDK.git', :branch => '0.0.1'

  target 'ExamplesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
