//
//  PaytomatSDKSimpleWallet.swift
//  Paytomat SDK
//
//  Created by Alex Melnichuk on 11/24/18.
//  Copyright © 2018 Baltic International Group OU. All rights reserved.
//

import Foundation

public extension PaytomatSDK {
    
    public typealias LoginRequest = SimpleWallet.LoginRequest
    public typealias TransferRequest = SimpleWallet.TransferRequest
    
    public class SimpleWallet {
        enum Action: String {
            case login = "login"
            case transfer = "transfer"
        }
        enum ProtocolName: String {
            case paytomat = "Paytomat"
        }
        enum Result: Int {
            case cancel = 0
            case success = 1
            case failure = 2
        }
    }
}

extension PaytomatSDK.SimpleWallet {
    
    public struct AppInfo {
        public let name: String
        public let iconUrl: String?
        public let version: String?
        public let description: String?
    }
    
    public struct LoginRequest: ToDictionaryConvertible {
        private struct Keys {
            static let appName = "dappName"
            static let appIcon = "dappIcon"
            static let appVersion = "version"
            static let appDescription = "loginMemo"
            static let loginUrl = "loginUrl"
            static let action = "action"
            static let `protocol` = "protocol"
            static let uuID = "uuID"
            static let callbackUrl = "callback"
        }
        
        public let appName: String
        public let appIcon: String?
        public let appVersion: String?
        public let appDescription: String?
        
        /// The unique id generated by dapp server for login verification.
        /// Needed only for Simple Wallet protocol.
        public let uuID: String
        
        /// The url on dapp server to accept the login validation information
        /// Needed only for Simple Wallet protocol.
        public let loginUrl: String?
        
        /// After user completes login, the wallet pulls up the callback URL of the app
        public let callbackUrl: String?
        
        public init(appName: String,
                    appIcon: String?,
                    appVersion: String?,
                    appDescription: String?,
                    uuID: String = "unset-uuid",
                    loginUrl: String? = nil,
                    callbackUrl: String? = nil) {
            self.appName = appName.trimmed()
            self.appIcon = appIcon?.trimmed()
            self.appVersion = appVersion?.trimmed()
            self.appDescription = appDescription?.trimmed()
            self.uuID = uuID.trimmed()
            self.loginUrl = loginUrl?.trimmed()
            self.callbackUrl = callbackUrl?.trimmed()
        }
        
        public init(app: AppInfo,
                    uuID: String = "unset-uuid",
                    loginUrl: String? = nil,
                    callbackUrl: String? = nil) {
            self.init(appName: app.name,
                      appIcon: app.iconUrl,
                      appVersion: app.version,
                      appDescription: app.description,
                      uuID: uuID,
                      loginUrl: loginUrl,
                      callbackUrl: callbackUrl)
        }
        
        func asDictionary() -> [String : Any?] {
            return [
                Keys.appName: appName,
                Keys.appIcon: appIcon,
                Keys.appVersion: appVersion,
                Keys.appDescription: appDescription,
                Keys.uuID: uuID,
                Keys.loginUrl: loginUrl,
                Keys.callbackUrl: callbackUrl,
                Keys.action: Action.login.rawValue,
                Keys.protocol: ProtocolName.paytomat.rawValue
            ]
        }
    }
    

    public struct TransferRequest: ToDictionaryConvertible {
        
        private struct Keys {
            static let appName = "dappName"
            static let appIcon = "dappIcon"
            static let appVersion = "version"
            static let appDescription = "desc"
            static let to = "to"
            static let amount = "amount"
            static let contract = "contract"
            static let symbol = "symbol"
            static let precision = "precision"
            static let memo = "dappData"
            static let action = "action"
            static let `protocol` = "protocol"
            static let callbackUrl = "callback"
        }
        
        public let appName: String
        public let appIcon: String?
        public let appVersion: String?
        public let appDescription: String?
        
        /// Recipient EOS account name
        public let to: String
        
        /// Transfer amount
        public let amount: Decimal
        
        /// Name of smart contract to be used by EOS transfer transaction
        /// eosio.token for EOS transfers
        public let contract: String
        
        /// Token symbol
        /// EOS for EOS transfers
        public let symbol: String
        
        /// Token precision
        /// 4 for EOS Transfers
        public let precision: UInt8
        
        /// Transfer memo. DApp can send data needed for trading
        public let memo: String?
        
        /// After user completes transfer, the wallet pulls up the callback URL of the app
        public let callbackUrl: String?
        
        public init(appName: String,
                    appIcon: String?,
                    appVersion: String?,
                    appDescription: String?,
                    to: String,
                    amount: Decimal,
                    contract: String,
                    symbol: String,
                    precision: UInt8,
                    memo: String?,
                    callbackUrl: String? = nil) {
            guard amount >= 0 else {
                preconditionFailure("TransferRequest.init amount cannot be negative")
            }
            
            self.appName = appName.trimmed()
            self.appIcon = appIcon?.trimmed()
            self.appVersion = appVersion?.trimmed()
            self.appDescription = appDescription?.trimmed()
            self.to = to.trimmed()
            self.amount = amount
            self.contract = contract.trimmed()
            self.symbol = symbol.trimmed()
            self.precision = precision
            self.memo = memo
            self.callbackUrl = callbackUrl?.trimmed()
        }
        
        public init(app: AppInfo,
                    to: String,
                    amount: Decimal,
                    contract: String,
                    symbol: String,
                    precision: UInt8,
                    memo: String?,
                    callbackUrl: String? = nil) {
            self.init(appName: app.name,
                      appIcon: app.iconUrl,
                      appVersion: app.version,
                      appDescription: app.description,
                      to: to,
                      amount: amount,
                      contract: contract,
                      symbol: symbol,
                      precision: precision,
                      memo: memo,
                      callbackUrl: callbackUrl)
        }
        
        func asDictionary() -> [String : Any?] {
            return [
                Keys.appName: appName,
                Keys.appIcon: appIcon,
                Keys.appVersion: appVersion,
                Keys.appDescription: appDescription,
                Keys.to: to,
                Keys.amount: amount.description,
                Keys.contract: contract,
                Keys.symbol: symbol,
                Keys.precision: precision,
                Keys.memo: memo,
                Keys.callbackUrl: callbackUrl,
                Keys.action: Action.transfer.rawValue,
                Keys.protocol: ProtocolName.paytomat.rawValue
            ]
        }
        
    }
}

